owner: ano-pedproject
repo: repo

sites:
  - name: Official
    url: https://pedproject.moscow
  - name: Pedacademy
    url: https://xn--80aakcbevmvw9p.xn--p1ai
  - name: Pedproject
    url: https://xn--d1abbusdciv.xn--p1ai
  - name: Yapedagog
    url: https://xn--80agabe1dc1k.xn--p1ai
  - name: Pedtalant
    url: https://xn--80aakd6ani0ae.xn--p1ai  
  - name: Rainbow
    url: https://xn----7sbabamch1evalo5aeg.xn--p1ai
  - name: Everest
    url: https://everest-edu.ru
  - name: Konkurs
    url: https://konkurs.pedproject.moscow
  - name: Vestnik
    url: https://vestnik.pedproject.moscow
    
status-website:
  baseUrl: /repo
  theme: dark
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Uptime monitor"
  introMessage: status page
  navbar:
    - title: Status
      href: /
